polar:
  access:
    token: ${POLAR_ACCESS_TOKEN}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polar_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
